const mongoose = require("mongoose");

const ImotSchema = {
  /*  category_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Category",
  }, */
  /*  information_id: {
    // type: mongoose.Schema.Types.ObjectId,
    // ref: "Category ",
  }, */
  title: String,
  description: String,
  thumbnail: String,
  // name: String,
  // child_name: String,
  // other_name: String,
  // age: String,
  // birth_date: String,
  // birth_location: String,
  // religion: String,
  // nation: String,
  // nrc: String,
  // height: String,
  // weight: String,
  // hair_color: String,
  // eyes_color: String,
  // prominent_sign: String,
  // department: String,
  // service_age: String,
  // current_address: String,
  // permanent_address: String,
  // education: String,
  // degree: String,
  // specialization: String,
  // degree_year_received: String,
  // grade: String,
  // first_degree: String,
  // graduate_degree: String,
  // school_attended: String,
  // from_years: String,
  // finished_years: String,
  // school_location: String,
  // school_level: String,
  // from_year_abroad: String,
  // finished_year_abroad: String,
  // countries_visited: String,
  // matter_of_visiting: String,
  // deposit_exchange: String,
  // father_name: String,
  // father_relative_name: String,
  // father_relativeness: String,
  // father_relativeness_gender: String,
  // father_relativeness_citizen: String,
  // father_relativeness_job: String,
  // father_relativeness_location: String,
  // father_relativeness_note: String,
  // //mother
  // mother_name: String,
  // mother_relative_name: String,
  // mother_relativeness: String,
  // mother_relativeness_gender: String,
  // mother_relativeness_citizen: String,
  // mother_relativeness_job: String,
  // mother_relativeness_location: String,
  // mother_relativeness_note: String,
  // //oversea
  // oversea_name: String,
  // oversea_relative_name: String,
  // oversea_relativeness: String,
  // oversea_relativeness_gender: String,
  // oversea_relativeness_citizen: String,
  // oversea_relativeness_job: String,
  // oversea_relativeness_location: String,
  // oversea_relativeness_note: String,
  // //wife or husband
  // love_name: String,
  // love_relative_name: String,
  // love_relativeness: String,
  // love_relativeness_gender: String,
  // love_relativeness_citizen: String,
  // love_relativeness_job: String,
  // love_relativeness_location: String,
  // love_relativeness_note: String,
  // //love father
  // love_father_name: String,
  // love_father_relative_name: String,
  // love_father_relativeness: String,
  // love_father_relativeness_gender: String,
  // love_father_relativeness_citizen: String,
  // love_father_relativeness_job: String,
  // love_father_relativeness_location: String,
  // love_father_relativeness_note: String,
  // //love mother
  // love_mother_name: String,
  // love_mother_relative_name: String,
  // love_mother_relativeness: String,
  // love_mother_relativeness_gender: String,
  // love_mother_relativeness_citizen: String,
  // love_mother_relativeness_job: String,
  // love_mother_relativeness_location: String,
  // love_mother_relativeness_note: String,
  // //son and daughter
  // child_name: String,
  // child_relative_name: String,
  // child_relativeness: String,
  // child_relativeness_gender: String,
  // child_relativeness_citizen: String,
  // child_relativeness_job: String,
  // child_relativeness_location: String,
  // child_relativeness_note: String,
  // //oversea-relative
  // oversea_relative_name: String,
  // oversea_relative_relativeness: String,
  // oversea_relative_nation: String,
  // oversea_relative_job: String,
  // oversea_relative_current_country: String,
  // oversea_relative_matter: String,
  // oversea_relative_return: String,
  // //
  // dept_action_taken: String,
  // dept_action_taken_fact: String,
  // dept_action_taken: String,
  // dept_punishment: String,
  // //
  // court_time: String,
  // court_fact: String,
  // court_action: String,
  // court_note: String,
  // //
  // degree_give_year: String,
  // what_type_degree: String,
  // degree_give_note: String,
  // //
  // go_abroad: String,
  // reason_go_abroad: String,
  // abroad_country: String,
  // arrive_time_abroad: String,
  // what_gov_abroad: String,
  // dept_when_arr_from_abroad: String,
  // need_to_go_abroad: String,
  // credentials_for_abroad: String,
  // //
  // submit_person_ticket: String,
  // submit_person_name: String,
  // submit_person_position: String,
  // submit_person_dept: String,
  // //
  // stuff_behavior: String,
  // //
  // date: Date,
  // //
  // submit_person1_ticket: String,
  // submit_person1_name: String,
  // submit_person1_position: String,
  // submit_person1_dept: String,
  // //
  // headmaster_ticket: String,
  // headmaster_name: String,
  // headmaster_position: String,
  // headmaster_dept: String,
  // headmaster_date: Date,
  // //
  // headmaster_ticket: String,
  // headmaster_name: String,
  // headmaster_position: String,
  // headmaster_dept: String,
  // headmaster_dept_date: Date,
  /* date: {
    type: Date,
    default: Date.now(),
  }, */
};

module.exports = mongoose.model("Information", ImotSchema);
